<div>
    @include('layouts.title',['title'=>'Dashboard'])
    @can('admin')
        @include('livewire.dashboard.admin')
    @endcan
    @canany(['pengguna','waiter','kasir','owner'])
        @include('livewire.dashboard.guest')
    @endcanany
</div>
